- name: Variable
  hosts: WEB
  vars:
    URL: google.com
  tasks:
    - name: print variable
      ansible.builtin.debig:
        msg: URL = {{ URL }}
    ## Ansible Access Variable with 2 flower brackets