- name: Variable
  hosts: localhost
  vars:
    URL: play.google.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
    ## Ansible Access Variable with 2 flower brackets
    - name: Print task Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.google.com